### ISSUE TITLE
Configuration examples

### ISSUE THREAD

**Issue by chrisdejager** [korotovsky/SingleSignOnServiceProviderBundle#1]
Hi!

Looks like your bundles provide an actual SSO provider/consumer with OTP through http. Kewl! 

Trying to get it to work. You introduced several new configuration options. I'm relatively new to symfony2 so I cannot guess this easily from code. Can you provide examples for the ServiceProvider and the IdentityProvider?

Thanx!
Chris

**Comment by korotovsky** [comment]
Hi @chrisdejager. Could I close this issue?
