### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by timmtim** [korotovsky/SingleSignOnServiceProviderBundle#2]
Could you please update the README with the correct documentation for the bundle. In the IdentityProvider bundle you refer to the ServiceProvider as Part 2 of the configuration, but there are no instructions whatsoever.

**Comment by korotovsky** [comment]
@timmtim On this week.

**Comment by timmtim** [comment]
@korotovsky Is it possible that you can provide us with some config snippets to get the bundle(s) up and running. We are upgrading from the old FMSsoBundle. We are struggling with the two bundles and their incompatibility on the base library. We want to use the "normal" routing, not the HTTP handler.

**Comment by korotovsky** [comment]
@timmtim Ok. But now you can already specify the latest versions of each bundles (`"korotovsky/sso-sp-bundle": "~0.2.0"` and `"korotovsky/sso-idp-bundle": "~0.2.0"`)

> We want to use the "normal" routing, not the HTTP handler.

What do you mean?

**Comment by timmtim** [comment]
@korotovsky "korotovsky/sso-sp-bundle": "~0.2.0" depends on version 0.1 of the library and "korotovsky/sso-idp-bundle" : "~0.2.0" depends on version 0.2 of the library.

**Comment by korotovsky** [comment]
@timmtim Oooh, i'm sorry fot that. Fixed in https://github.com/korotovsky/SingleSignOnServiceProviderBundle/commit/eac0b009cfeb90bda42d90babaacf495317a2c5b

**Comment by korotovsky** [comment]
Hi @timmtim. 

Sorry for the delay :) I've just updated `README.md` in `0.1.x` and `0.2.x` and added some new tests.
