### ISSUE TITLE
undefined service krtv_single_sign_on_service_provider.context_factory

### ISSUE THREAD

**Issue by kendrick-k** [korotovsky/SingleSignOnServiceProviderBundle#5]
Hello, it seems the service is undefined : krtv_single_sign_on_service_provider.context_factory into services.xml ?

For debugging purposes I added locally : 

<parameter key="krtv_single_sign_on_service_provider.context_factory.class">Krtv\Bundle\SingleSignOnServiceProviderBundle\Context\AuthenticationContextFactory</parameter>

    </parameters>

& 

        <service id="krtv_single_sign_on_service_provider.context_factory" class="%krtv_single_sign_on_service_provider.context_factory.class%">
            <argument type="collection"></argument>
            <argument type="string"></argument>
        </service>

to make it run. Any ideas ? Thanks !

**Comment by kendrick-k** [comment]
ServiceNotFoundException in CheckExceptionOnInvalidReferenceBehaviorPass.php line 58:
The service "krtv_single_sign_on_service_provider.security.authentication.entry_point" has a dependency on a non-existent service "krtv_single_sign_on_service_provider.context_factory".

**Comment by korotovsky** [comment]
Hi! Sorry for the delay,

This service has to be created automatically here https://github.com/korotovsky/SingleSignOnServiceProviderBundle/blob/0.3.x/src/Krtv/Bundle/SingleSignOnServiceProviderBundle/Factory/SingleSignOnFactory.php#L118.

What I would suggest: check why Symfony does not execute this method. Please let me know why and we will decide how to fix it in a better way.

**Comment by mediafigaro** [comment]
Hello thanks for the info, here is the error I have : 
![context_factory](https://cloud.githubusercontent.com/assets/18629935/21320868/c055368e-c612-11e6-9e91-3b2336459b2b.jpg)

**Comment by mediafigaro** [comment]
only parameters defined : 

<parameter key="krtv_single_sign_on_service_provider.context_factory.class">Krtv\Bundle\SingleSignOnServiceProviderBundle\Context\AuthenticationContextFactory</parameter>
<parameter key="krtv_single_sign_on_service_provider.context_factory.attribute">_sso_context</parameter>

**Comment by korotovsky** [comment]
Hi,

Actually it's not a root of the problem. As I mentioned above, this service have to be added to the container "on the fly". Since you either don't have an entrypoint, or you didn't define a sso firewall. That's why it wasn't created.

**Comment by mediafigaro** [comment]
yes sure but what am I missing, I just applied what is on the doc : https://github.com/korotovsky/SingleSignOnServiceProviderBundle I need some extra configuration ? thanks

**Comment by mediafigaro** [comment]
yes : 

`
security:

    providers:
        in_memory:
            memory: ~

    firewalls:
    
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            sso:
                require_previous_session: false
                provider:                 main
                check_path:               /otp/validate/     # Same as in app/config/routing.yml

                sso_scheme:               http               # Required
                sso_host:                 idp.example.com    # Required

                sso_otp_scheme:           http               # Optional
                sso_otp_host:             consumer1.com      # Optional

                sso_failure_path:         /login             # Can also be as an absolute path to service provider
                sso_path:                 /sso/login/        # SSO endpoint on IdP.

                sso_service_extra:           null            # Default service extra parameters. Optional.
                sso_service_extra_parameter: service_extra   # Parameter name. Optional

                sso_login_required:           1              # Optional
                sso_login_required_parameter: login_required # Optional

                sso_service:                  consumer1      # Consumer name

            logout:
                invalidate_session: true
                path:               /logout
                target:             http://idp.example.com/sso/logout?service=consumer1`

**Comment by mediafigaro** [comment]
ok I have this now : 

` [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                                   
  The service "security.authentication.provider.krtv_single_sign_on_service_provider.main" has a dependency on a non-existent service "security.user.provider.concrete.main". `

**Comment by mediafigaro** [comment]
Is there some services to setup too ? eg. https://github.com/korotovsky/SingleSignOnIdentityProviderBundle/issues/10

**Comment by korotovsky** [comment]
Have you added this bundle to the list of bundles?

```
// AppKernel.php

class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = array(
            new Krtv\Bundle\SingleSignOnServiceProviderBundle\KrtvSingleSignOnServiceProviderBundle(),

// ...
```

**Comment by mediafigaro** [comment]
yes !

**Comment by korotovsky** [comment]
Does it mean "you added it a time ago" or "it works now"?)

**Comment by mediafigaro** [comment]
I mean it was included, I just applied your doc. I have this : 

ok I have this now :

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException] The service "security.authentication.provider.krtv_single_sign_on_service_provider.main" has a dependency on a non-existent service "security.user.provider.concrete.main".

(entrypoint is called)

**Comment by korotovsky** [comment]
Actually, your security configuration looks fine, because:

```
providers:
    in_memory: # <---- THIS KEY
        memory: ~

firewalls:
    main:
        pattern: ^/
        sso:
            require_previous_session: false
            provider:                 in_memory # <--- HAVE TO BE SAME
```

**Comment by mediafigaro** [comment]
ok sure, thanks it's a Sf configuration point...! now : 

RuntimeException in ServiceManager.php line 51:
No ServiceProvider managers found. Make sure that you have at least one ServiceProvider manager tagged with "sso.service_provider"

**Comment by korotovsky** [comment]
Please, follow the instructions: https://github.com/korotovsky/SingleSignOnIdentityProviderBundle#step-3-create-service-providers

**Comment by mediafigaro** [comment]
ok I see, finally I got mixed up in between the two apps. thanks, I'll let you know.
