### ISSUE TITLE
Guzzle / OTP process

### ISSUE THREAD

**Issue by mediafigaro** [korotovsky/SingleSignOnServiceProviderBundle#6]
Hello & thanks again for your great work !

I've restarted the project on a clean installation and now it's better. I still have some troubles and I suppose some misunderstanding : 

1- when the consumer is called I get redirected to the idp uri but I always have a Malformed uri : 
`false === $httpUtils->checkUrl($request->getSchemeAndHttpHost().$request->getRequestUri())`

this should be a secret problem I suppose (hash control?) : I do have the same secret keyword into parameters and consumer conf secret_parameter. Any ideas ?

2- in the meantime I removed the exception to follow up & I so I get redirected to the login form (just installed a minimal SF login process), after login on idp with the correct credentials I get the json (correct) response from internal/v1/sso/ instead of arriving to the landing page. It's an url redirect ? It must be a guzzle configuration problem ?

thanks

btw you can have a look at this [docker for symfony](https://github.com/mediafigaro/docker-symfony)

**Comment by korotovsky** [comment]
Hi,

1. First of all, secrets have to be the same on both applications for SSO sub-system. You can check it inside compiled DI container for authentication system.

2. I can check it a bit later.

**Comment by mediafigaro** [comment]
Hello, yes it seems fine for 1. For 2 maybe I'm missing something in the process...

**Comment by korotovsky** [comment]
@mediafigaro ping
