### ISSUE TITLE
Сyclical redirection

### ISSUE THREAD

**Issue by vacslav-dev** [korotovsky/SingleSignOnServiceProviderBundle#7]
When you go to the page there is a cyclic redirect on sso login service after authorize.
sso.client -> sso.service (authorize) -> sso.client -> i.tp

**Comment by korotovsky** [comment]
It often happens when SP can't validate provided OTP from IdP and fails to cyclical loop. Check it first.

**Comment by korotovsky** [comment]
@vacslav-dev ping

**Comment by vacslav-dev** [comment]
The problem was that the user was searched in another data-provider. It's decided. Thank you.
